[package]
name = "vga-efi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.10"
uart_16550 = "0.2.14"
spin = "0.9.2"
x86_64 = "*"

driver-vga = { path = "../vga"}