[package]
name = "kernel-memory"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
x86_64 = "0.14.8"
linked_list_allocator = "0.9.1"
bootloader = "0.10.12"
lazy_static = "1.4.0"
spin = "0.9.2"