[package]
name = "builder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader-locator = "0.0.4"
runner-utils = "0.0.2"
locate-cargo-manifest = "0.2.0"
cargo_toml = "0.11.4"
toml = "0.5.8"